apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/turkardiksha345-oss/Application-Deployment.git
    targetRevision: main
    path: helm/game-app
    helm:
      values: |
        backend:
          replicaCount: 3
          image:
            repository: jfrogtrail1.jfrog.io/docker-local-docker-local/backend
            tag: latest
        frontend:
          replicaCount: 2
          image:
            repository: jfrogtrail1.jfrog.io/docker-local-docker-local/frontend
            tag: latest
        global:
          environment: production
  destination:
    server: https://kubernetes.default.svc
    namespace: game-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
    - name: Documentation
      value: https://github.com/turkardiksha345-oss/Application-Deployment
    - name: Support
      value: devops@company.com
---
apiVersion: v1
kind: Namespace
metadata:
  name: game-app
  labels:
    app.kubernetes.io/name: game-app
    app.kubernetes.io/managed-by: argocd
