name: Application Deployment Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  REGISTRY: jfrogtrail1.jfrog.io
  REPOSITORY: docker-local-docker-local

jobs:

  build-and-push:

    name: Build And Push Docker Images

    runs-on: [self-hosted, linux, x64, docker]

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Short Commit SHA
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login To JFrog
        run: |
          echo "${{ secrets.JFROG_PASSWORD }}" | docker login \
          -u "${{ secrets.JFROG_USERNAME }}" \
          --password-stdin \
          ${{ env.REGISTRY }}

      # Backend Build

      - name: Build Backend Docker Image
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY/backend:${SHORT_SHA} \
          -t $REGISTRY/$REPOSITORY/backend:latest \
          ./backend

      - name: Push Backend Docker Image
        run: |
          docker push $REGISTRY/$REPOSITORY/backend:${SHORT_SHA}
          docker push $REGISTRY/$REPOSITORY/backend:latest

      # Frontend Build

      - name: Build Frontend Docker Image
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY/frontend:${SHORT_SHA} \
          -t $REGISTRY/$REPOSITORY/frontend:latest \
          ./frontend

      - name: Push Frontend Docker Image
        run: |
          docker push $REGISTRY/$REPOSITORY/frontend:${SHORT_SHA}
          docker push $REGISTRY/$REPOSITORY/frontend:latest

  update-helm:

    name: Update Helm Values

    runs-on: [self-hosted, linux, x64, docker]

    needs: build-and-push

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Short Commit SHA
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update Backend Image Tag
        run: |
          sed -i "/backend:/,/pullPolicy:/ s/tag:.*/tag: ${SHORT_SHA}/" helm/game-app/values.yaml

      - name: Update Frontend Image Tag
        run: |
          sed -i "/frontend:/,/pullPolicy:/ s/tag:.*/tag: ${SHORT_SHA}/" helm/game-app/values.yaml

      - name: Commit And Push Helm Changes
        run: |

          git config --global user.name "github-actions"

          git config --global user.email "github-actions@github.com"

          git add helm/game-app/values.yaml

          git commit -m "Update image tags to ${SHORT_SHA}" || echo "No changes to commit"

          git push

  deploy-argocd:

    name: Deploy Using ArgoCD

    runs-on: [self-hosted, linux, x64, docker]

    needs: update-helm

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login To ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
          --username ${{ secrets.ARGOCD_USERNAME }} \
          --password ${{ secrets.ARGOCD_PASSWORD }} \
          --insecure

      - name: Create ArgoCD Application
        run: |

          argocd app create my-application \
          --repo https://github.com/turkardiksha345-oss/Application-Deployment-Repo.git \
          --path helm/game-app \
          --dest-server https://kubernetes.default.svc \
          --dest-namespace default \
          --sync-policy automated \
          --auto-prune \
          --self-heal \
          --upsert

      - name: Wait For Healthy Status
        run: |
          argocd app wait my-application \
          --health \
          --timeout 300